### ISSUE TITLE
imread error for MG learn

### ISSUE THREAD

**Issue by odeharary** [amueller/mglearn#5] opened 2018-01-16 18:42 UTC
I did some research and I believe the issue stems from 'imread' no longer being part of SCIPY. 

ImportError                               Traceback (most recent call last)
<ipython-input-35-c4d0c4784e8d> in <module>()
      2 
      3 
----> 4 import mglearn

~\AppData\Local\Continuum\anaconda3\lib\site-packages\mglearn\__init__.py in <module>()
----> 1 from . import plots
      2 from . import tools
      3 from .plots import cm3, cm2
      4 from .tools import discrete_scatter
      5 from .plot_helpers import ReBl

~\AppData\Local\Continuum\anaconda3\lib\site-packages\mglearn\plots.py in <module>()
      1 from .plot_linear_svc_regularization import plot_linear_svc_regularization
----> 2 from .plot_interactive_tree import plot_tree_progressive, plot_tree_partition
      3 from .plot_animal_tree import plot_animal_tree
      4 from .plot_rbf_svm_parameters import plot_svm
      5 from .plot_knn_regression import plot_knn_regression

~\AppData\Local\Continuum\anaconda3\lib\site-packages\mglearn\plot_interactive_tree.py in <module>()
      6 from sklearn.externals.six import StringIO  # doctest: +SKIP
      7 from sklearn.tree import export_graphviz
----> 8 from scipy.misc import imread
      9 from scipy import ndimage
     10 from sklearn.datasets import make_moons

ImportError: cannot import name 'imread'

**Comment by amueller** [comment] 2018-01-16 18:43
you need to install pillow.

**Comment by odeharary** [comment] 2018-01-16 18:48
I already have pillow

**Comment by amueller** [comment] 2018-01-16 18:51
hm that's strange. Sorry you're having difficulties. Is pillow installed in the same environment
in which you want to run the code?

What version of scipy do you have and what version of PIL?
```python
import scipy
print(scipy.__version__)
import PIL
print(PIL.__version__)
```

**Comment by odeharary** [comment] 2018-01-16 18:59
Scipy: 0.19.1
pil: 4.2.1

**Comment by amueller** [comment] 2018-01-16 19:00
And if you try to import ``imread`` directly in this environment with
```python
 from scipy.misc import imread
```
you get the same error?

**Comment by odeharary** [comment] 2018-01-16 19:01
Yeah - I get the same error. if you look at this link you can see its discontinued 
https://docs.scipy.org/doc/scipy/reference/generated/scipy.misc.imread.html

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-51-f9d3d927b58f> in <module>()
----> 1 from scipy.misc import imread

ImportError: cannot import name 'imread'

**Comment by amueller** [comment] 2018-01-16 19:05
It's deprecated in 1.2.0. That's not the reason you're seeing this error. It will work until ``1.2.0`` as you can see from that link. You have ``0.19.1``.
The issue is that scipy can not find ``PIL``, I think. Maybe try updating scipy? Also see #5.

**Comment by odeharary** [comment] 2018-01-16 19:06
Ive spent a couple hours on this already. will proceed without mglearn.

**Comment by amueller** [comment] 2018-01-16 19:06
Some places suggest ``conda uninstall PIL`` followed by ``conda install pillow``. Well this is not really an mglearn issue. It's a scipy issue (or maybe a conda issue?)

**Comment by amueller** [comment] 2018-01-16 19:07
If you want a quick fix, try replacing the import by ``from scipy.misc.pilutil import imread`` seemed to help some, though I have no idea why.

**Comment by fjcaro2003** [comment] 2018-05-07 11:19
Its works!

**Comment by amueller** [comment] 2020-05-20 16:33
should be fixed now by using imageio

**Closed as completed by amueller** 2020-05-20 16:33 UTC
